/**
 * This code was generated by Builder.io.
 */
import React from "react";
import styles from "./CustomerList.module.css";
import CustomerRow from "./CustomerRow";

const customers = [
  {
    id: 1,
    name: "Bessie Cooper",
    joinDate: "August 2, 2013",
    gender: "Male",
    phone: "8978675634",
  },
  {
    id: 2,
    name: "Devon Lane",
    joinDate: "May 6, 2012",
    gender: "Female",
    phone: "9897652342",
  },
  {
    id: 3,
    name: "Marvin McKinney",
    joinDate: "October 25, 2019",
    gender: "Female",
    phone: "9876543256",
  },
  {
    id: 4,
    name: "Floyd Miles",
    joinDate: "December 29, 2012",
    gender: "Male",
    phone: "6578364578",
  },
  {
    id: 5,
    name: "Jacob Jones",
    joinDate: "September 9, 2013",
    gender: "Male",
    phone: "9876543256",
  },
  {
    id: 6,
    name: "Annette Black",
    joinDate: "May 20, 2015",
    gender: "Female",
    phone: "9876543256",
  },
  {
    id: 7,
    name: "Jenny Wilson",
    joinDate: "February 11, 2014",
    gender: "Male",
    phone: "9876543256",
  },
  {
    id: 8,
    name: "Jane Cooper",
    joinDate: "November 28, 2015",
    gender: "Female",
    phone: "6578364578",
  },
  {
    id: 9,
    name: "Robert Fox",
    joinDate: "February 9, 2015",
    gender: "Female",
    phone: "9876543256",
  },
  {
    id: 10,
    name: "Eleanor Pena",
    joinDate: "December 2, 2018",
    gender: "Male",
    phone: "6578364578",
  },
  {
    id: 11,
    name: "Darlene Robertson",
    joinDate: "April 28, 2016",
    gender: "Male",
    phone: "8978675634",
  },
  {
    id: 12,
    name: "Dianne Russell",
    joinDate: "May 29, 2017",
    gender: "Female",
    phone: "9897652342",
  },
  {
    id: 13,
    name: "Wade Warren",
    joinDate: "October 30, 2017",
    gender: "Female",
    phone: "9897652342",
  },
  {
    id: 14,
    name: "Guy Hawkins",
    joinDate: "August 7, 2017",
    gender: "Male",
    phone: "6578364578",
  },
  {
    id: 15,
    name: "Esther Howard",
    joinDate: "November 16, 2014",
    gender: "Female",
    phone: "8978675634",
  },
  {
    id: 16,
    name: "Savannah Nguyen",
    joinDate: "October 31, 2017",
    gender: "Female",
    phone: "9876543256",
  },
  {
    id: 17,
    name: "Robert Fox",
    joinDate: "August 24, 2013",
    gender: "Female",
    phone: "(303) 555-0105",
  },
];

function CustomerTable() {
  return (
    <div className={styles.tableWrapper}>
      <table className={styles.customerTable}>
        <thead>
          <tr>
            <th>Sr No.</th>
            <th>
              Name{" "}
            </th>
            <th>
              Date of Joining{" "}
            </th>
            <th>
              Gender{" "}
            </th>
            <th>
              Phone{" "}
            </th>
            <th>Action</th>
          </tr>
        </thead>
        <tbody>
          {customers.map((customer, index) => (
            <CustomerRow key={customer.id} customer={customer} index={index} />
          ))}
        </tbody>
      </table>
    </div>
  );
}

export default CustomerTable;
