/**
 * This code was generated by Builder.io.
 */
import React from "react";
import styles from "./CustomerList.module.css";
import CustomerRow from "./CustomerRow";

const customers = [
  {
    id: 1,
    name: "Bessie Cooper",
    joinDate: "August 2, 2013",
    gender: "Male",
    phone: "8978675634",
  },
  {
    id: 2,
    name: "Devon Lane",
    joinDate: "May 6, 2012",
    gender: "Female",
    phone: "9897652342",
  },
  {
    id: 3,
    name: "Marvin McKinney",
    joinDate: "October 25, 2019",
    gender: "Female",
    phone: "9876543256",
  },
  {
    id: 4,
    name: "Floyd Miles",
    joinDate: "December 29, 2012",
    gender: "Male",
    phone: "6578364578",
  },
  {
    id: 5,
    name: "Jacob Jones",
    joinDate: "September 9, 2013",
    gender: "Male",
    phone: "9876543256",
  },
  {
    id: 6,
    name: "Annette Black",
    joinDate: "May 20, 2015",
    gender: "Female",
    phone: "9876543256",
  },
  {
    id: 7,
    name: "Jenny Wilson",
    joinDate: "February 11, 2014",
    gender: "Male",
    phone: "9876543256",
  },
  {
    id: 8,
    name: "Jane Cooper",
    joinDate: "November 28, 2015",
    gender: "Female",
    phone: "6578364578",
  },
  {
    id: 9,
    name: "Robert Fox",
    joinDate: "February 9, 2015",
    gender: "Female",
    phone: "9876543256",
  },
  {
    id: 10,
    name: "Eleanor Pena",
    joinDate: "December 2, 2018",
    gender: "Male",
    phone: "6578364578",
  },
  {
    id: 11,
    name: "Darlene Robertson",
    joinDate: "April 28, 2016",
    gender: "Male",
    phone: "8978675634",
  },
  {
    id: 12,
    name: "Dianne Russell",
    joinDate: "May 29, 2017",
    gender: "Female",
    phone: "9897652342",
  },
  {
    id: 13,
    name: "Wade Warren",
    joinDate: "October 30, 2017",
    gender: "Female",
    phone: "9897652342",
  },
  {
    id: 14,
    name: "Guy Hawkins",
    joinDate: "August 7, 2017",
    gender: "Male",
    phone: "6578364578",
  },
  {
    id: 15,
    name: "Esther Howard",
    joinDate: "November 16, 2014",
    gender: "Female",
    phone: "8978675634",
  },
  {
    id: 16,
    name: "Savannah Nguyen",
    joinDate: "October 31, 2017",
    gender: "Female",
    phone: "9876543256",
  },
  {
    id: 17,
    name: "Robert Fox",
    joinDate: "August 24, 2013",
    gender: "Female",
    phone: "(303) 555-0105",
  },
];

function CustomerTable() {
  return (
    <div className={styles.tableWrapper}>
      <table className={styles.customerTable}>
        <thead>
          <tr>
            <th className={styles.checkboxHeader}>
              <input
                type="checkbox"
                id="selectAll"
                className={styles.visuallyHidden}
              />
              <label
                htmlFor="selectAll"
                className={styles.customCheckbox}
              ></label>
            </th>
            <th>Sr No.</th>
            <th>
              Name{" "}
              <img
                src="https://cdn.builder.io/api/v1/image/assets/TEMP/84c4e3d9e20bccdda0cced04b5377b918b01d924efe8bc7475650bfc83e64b41?apiKey=dfc7dbfa76d043c4a69edcbff91a85cb&&apiKey=dfc7dbfa76d043c4a69edcbff91a85cb"
                alt=""
                className={styles.sortIcon}
              />
            </th>
            <th>
              Date of Joining{" "}
              <img
                src="https://cdn.builder.io/api/v1/image/assets/TEMP/7cffa7c1a8d1e3dbfe824b14fe328d4fa2e096f2b3c1ae82099f9c576568913a?apiKey=dfc7dbfa76d043c4a69edcbff91a85cb&&apiKey=dfc7dbfa76d043c4a69edcbff91a85cb"
                alt=""
                className={styles.sortIcon}
              />
            </th>
            <th>
              Gender{" "}
              <img
                src="https://cdn.builder.io/api/v1/image/assets/TEMP/1df7c50c1ac1a483b8bd50ba380bd3fc779484892ca733ac7c81bb59bc5f5cee?apiKey=dfc7dbfa76d043c4a69edcbff91a85cb&&apiKey=dfc7dbfa76d043c4a69edcbff91a85cb"
                alt=""
                className={styles.sortIcon}
              />
            </th>
            <th>
              Phone{" "}
              <img
                src="https://cdn.builder.io/api/v1/image/assets/TEMP/54b40acc0cf81043933d978c8c93845249b74d68a0d42b1e9a85844f8e8a0ef1?apiKey=dfc7dbfa76d043c4a69edcbff91a85cb&&apiKey=dfc7dbfa76d043c4a69edcbff91a85cb"
                alt=""
                className={styles.sortIcon}
              />
            </th>
            <th>Action</th>
          </tr>
        </thead>
        <tbody>
          {customers.map((customer, index) => (
            <CustomerRow key={customer.id} customer={customer} index={index} />
          ))}
        </tbody>
      </table>
    </div>
  );
}

export default CustomerTable;
