/**
 * This code was generated by Builder.io.
 */
import React from "react";
import styles from "./CustomerList.module.css";

function CustomerRow({ customer, index }) {
  const rowClass = index % 2 === 0 ? styles.evenRow : styles.oddRow;

  return (
    <tr className={rowClass}>
      <td>
        <input
          type="checkbox"
          id={`select-${customer.id}`}
          className={styles.visuallyHidden}
        />
        <label
          htmlFor={`select-${customer.id}`}
          className={styles.customCheckbox}
        ></label>
      </td>
      <td>{customer.id}</td>
      <td>{customer.name}</td>
      <td>{customer.joinDate}</td>
      <td>{customer.gender}</td>
      <td>{customer.phone}</td>
      <td>
        <button className={styles.actionButton}>
          <img
            src={`http://b.io/ext_${8 + (index % 3)}-`}
            alt="Action"
            className={styles.actionIcon}
          />
        </button>
      </td>
    </tr>
  );
}

export default CustomerRow;
