/**
 * This code was generated by Builder.io.
 */
import React from "react";
import styles from "./CustomerList.module.css";

function CustomerRow({ customer, index }) {
  const rowClass = index % 2 === 0 ? styles.evenRow : styles.oddRow;

  return (
    <tr className={rowClass}>
      <td>{customer.id}</td>
      <td>{customer.name}</td>
      <td>{customer.joinDate}</td>
      <td>{customer.gender}</td>
      <td>{customer.phone}</td>
      <td>
        <div class="dropdown">
          <span type="button" data-bs-toggle="dropdown" aria-expanded="false">
            <i class="bi bi-three-dots-vertical"></i>
          </span>
          <ul class="dropdown-menu">
            <li>
              <a class="dropdown-item" href="/">
                Edit
              </a>
            </li>
            <li>
              <a class="dropdown-item" href="/">
                Delete
              </a>
            </li>
          </ul>
        </div>
      </td>
    </tr>
  );
}

export default CustomerRow;
