/**
 * This code was generated by Builder.io.
 */
import React from "react";
import styles from "./CustomerList.module.css";

function FilterOptions() {
  return (
    <div className={styles.filterOptions}>
      <div className={styles.genderFilter}>
        <div className={styles.filterOption}>
          <div className={styles.radioWrapper}>
            <input
              type="radio"
              id="male"
              name="gender"
              className="form-check-input"
              checked
            />
            <label htmlFor="male" className="form-label mb-0">
              Male
            </label>
          </div>
        </div>
        <div className={styles.filterOption}>
          <div className={styles.radioWrapper}>
            <input
              type="radio"
              id="female"
              name="gender"
              className="form-check-input"
            />
            <label htmlFor="female" className="form-label mb-0">
              Female
            </label>
          </div>
        </div>
      </div>
      <div className={styles.dateFilter}>
        <input type="date" className={styles.userDate} />
      </div>
      <div className={styles.departmentFilter}>
        <select
          className={styles.userSelect}
          aria-label="Default select example"
        >
          <option selected>Department</option>
          <option value="1">One</option>
          <option value="2">Two</option>
          <option value="3">Three</option>
        </select>
      </div>
    </div>
  );
}

export default FilterOptions;
