/**
 * This code was generated by Builder.io.
 */
import React from "react";
import styles from "./CustomerList.module.css";

function FilterOptions() {
  return (
    <div className={styles.filterOptions}>
      <div className={styles.genderFilter}>
        <div className={styles.filterOption}>
          <div className={styles.radioWrapper}>
            <input
              type="radio"
              id="male"
              name="gender"
              className={styles.visuallyHidden}
            />
            <label htmlFor="male" className={styles.radioLabel}>
              <span className={styles.customRadio}></span>
              Male
            </label>
          </div>
        </div>
        <div className={styles.filterOption}>
          <div className={styles.radioWrapper}>
            <input
              type="radio"
              id="female"
              name="gender"
              className={styles.visuallyHidden}
            />
            <label htmlFor="female" className={styles.radioLabel}>
              <span className={styles.customRadio}></span>
              Female
            </label>
          </div>
        </div>
      </div>
      <div className={styles.dateFilter}>
        <img
          src="https://cdn.builder.io/api/v1/image/assets/TEMP/3a86b7163647062fb0db16b21487ffb5c5aef3c47cf670a96c772edd53befbb2?apiKey=dfc7dbfa76d043c4a69edcbff91a85cb&&apiKey=dfc7dbfa76d043c4a69edcbff91a85cb"
          alt=""
          className={styles.calendarIcon}
        />
        <span className={styles.dateRange}>13/04/2022 - 11/05/2022</span>
        <img
          src="https://cdn.builder.io/api/v1/image/assets/TEMP/085ac558ba9d6de1795147ee05aecbb39f027086375461dba6e022b010aad148?apiKey=dfc7dbfa76d043c4a69edcbff91a85cb&&apiKey=dfc7dbfa76d043c4a69edcbff91a85cb"
          alt=""
          className={styles.dropdownIcon}
        />
      </div>
      <div className={styles.departmentFilter}>
        <span>Department</span>
        <img
          src="https://cdn.builder.io/api/v1/image/assets/TEMP/085ac558ba9d6de1795147ee05aecbb39f027086375461dba6e022b010aad148?apiKey=dfc7dbfa76d043c4a69edcbff91a85cb&&apiKey=dfc7dbfa76d043c4a69edcbff91a85cb"
          alt=""
          className={styles.dropdownIcon}
        />
      </div>
    </div>
  );
}

export default FilterOptions;
