/**
 * This code was generated by Builder.io.
 */
import React from "react";
import styles from "./CustomerList.module.css";

function Pagination() {
  return (
    <nav className={styles.pagination} aria-label="Customer list pagination">
      <div className={styles.paginationInfo}>
        <span className={styles.visuallyHidden}>Showing 11 - 21 out of 88</span>
      </div>
      <ul className={styles.pageList}>
        <li>
          <button className={styles.pageButton} aria-label="Previous page">
            <img
              src="https://cdn.builder.io/api/v1/image/assets/TEMP/b96ebe45c83d9ce848422d02be374574c83f9cec6dbbb43b961ba17dc4281eba?apiKey=dfc7dbfa76d043c4a69edcbff91a85cb&&apiKey=dfc7dbfa76d043c4a69edcbff91a85cb"
              alt=""
              className={styles.pageIcon}
            />
          </button>
        </li>
        <li>
          <button className={styles.pageButton}>1</button>
        </li>
        <li>
          <button className={styles.pageButton}>2</button>
        </li>
        <li>
          <button className={`${styles.pageButton} ${styles.activePage}`}>
            3
          </button>
        </li>
        <li>
          <button className={styles.pageButton}>4</button>
        </li>
        <li>
          <button className={styles.pageButton}>5</button>
        </li>
        <li>
          <button className={styles.pageButton}>...</button>
        </li>
        <li>
          <button className={styles.pageButton}>45</button>
        </li>
        <li>
          <button className={styles.pageButton} aria-label="Next page">
            <img
              src="https://cdn.builder.io/api/v1/image/assets/TEMP/27903a4c0d2bbcec6520ff249c4f7190b14f4ac7181e9e89dfeb0bc22d0fc73a?apiKey=dfc7dbfa76d043c4a69edcbff91a85cb&&apiKey=dfc7dbfa76d043c4a69edcbff91a85cb"
              alt=""
              className={styles.pageIcon}
            />
          </button>
        </li>
      </ul>
      <div className={styles.itemsPerPage}>
        <span>Item Per Page</span>
        <div className={styles.itemsSelect}>
          <span>20</span>
          <img
            src="https://cdn.builder.io/api/v1/image/assets/TEMP/1762dac157dcc1abe2e362f6a73108f32221c9469bccb09a4414c385229b08f8?apiKey=dfc7dbfa76d043c4a69edcbff91a85cb&&apiKey=dfc7dbfa76d043c4a69edcbff91a85cb"
            alt=""
            className={styles.dropdownIcon}
          />
        </div>
      </div>
    </nav>
  );
}

export default Pagination;
