/**
 * This code was generated by Builder.io.
 */
import React from "react";
import styles from "./CustomerList.module.css";

function SearchBar() {
  return (
    <form className={styles.searchForm}>
      <div className={styles.inputWrapper}>
        <label htmlFor="searchInput" className={styles.visuallyHidden}>
          Search customers
        </label>
        <input
          id="searchInput"
          type="text"
          className={styles.searchInput}
          placeholder="Search..."
          aria-label="Search customers"
        />
        <img
          src="https://cdn.builder.io/api/v1/image/assets/TEMP/044b305bbf4f17133216a8adbab107f0a6dc00be5fd9b4fb45d0871c410ee720?apiKey=dfc7dbfa76d043c4a69edcbff91a85cb&&apiKey=dfc7dbfa76d043c4a69edcbff91a85cb"
          alt=""
          className={styles.searchIcon}
        />
      </div>
      <button type="submit" className={styles.searchButton}>
        Search
      </button>
    </form>
  );
}

export default SearchBar;
