/**
 * This code was generated by Builder.io.
 */
import React from "react";
import styles from "./CustomerList.module.css";

function SearchBar() {
  return (
    <form className={styles.searchForm}>
      <div className={styles.inputWrapper}>
        <input
          id="searchInput"
          type="text"
          className="form-control-plaintext"
          placeholder="Search..."
          aria-label="Search customers"
        />
        <i class="bi bi-search"></i>
      </div>
      <button type="submit" className={styles.searchButton}>
        Search
      </button>
    </form>
  );
}

export default SearchBar;
